import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import LayoutWrapper from "@/src/layout";
import "./globals.css";
import Link from "next/link";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <LayoutWrapper>
          <div className="text-center py-8">
            <Link
              href="/"
              className="text-5xl md:text-6xl font-bold bg-linear-to-r from-purple-600 via-pink-600 to-blue-600 bg-clip-text text-transparent mb-4"
            >
              Anime Universe
            </Link>
            <p className="text-xl text-gray-600 dark:text-gray-400 font-medium">
              Discover your next favorite anime ✨
            </p>
          </div>
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
